### ISSUE TITLE
Windows 10 window sizing / spacing leaves margin between windows

### ISSUE THREAD

**Issue by fredkilbourn** [DannyBen/Gridy#1]
@DannyBen I seem to be having a problem with Gridy on Windows 10 when it comes to calculating window size / position and snapping windows to a grid.  See attached image, there is a margin between the windows when aligned with Gridy.  I also left this as a comment on the Gridy product page.

![gridy](https://cloud.githubusercontent.com/assets/658757/8989021/293955c6-36af-11e5-9cdd-8d0f9e4d025b.png)

**Comment by DannyBen** [comment]
Maybe they just made the borders transparent instead of removing them. Anyways, it will probably take some time until I upgrade to Windows 10.

**Comment by fredkilbourn** [comment]
Okay - FYI I just did the upgrade today and it went very smooth, this is the only bug I've found across a vast base of installed software :)

**Comment by fredkilbourn** [comment]
@DannyBen Sorry to bump you on this but it's been almost a year.  I know it (understandably) isn't a high priority but think you might have time to peek at this sometime?

**Comment by DannyBen** [comment]
I actually did take a look, several times. WIndows 10 has an invisible border that is reported as part of the window size and position. I have not reached any decent solutions. I am open to suggestions or a PR.

[These are](https://github.com/DannyBen/Gridy/blob/master/Gridy.ahk#L456-L501) the areas in the code that probably need the attention.

**Comment by fredkilbourn** [comment]
I'm not very fluent in Windows GUI APIs or the language this is written in, but this is a relatively new answer on stackoverflow that might put us on the right path: [http://stackoverflow.com/a/37311902]

I don't know if the mentioned APIs can be called easily with this language, but might be a starting point nonetheless.

If i find spare time I might try and hack on it.

**Comment by fredkilbourn** [comment]
Here's another windows manager written in AutoHotKey that (from reading commit notes) seems to have compensated for this issue.  Link to the relevant function that might be of use: [https://github.com/fuhsjr00/bug.n/blob/master/src/Window.ahk#L75]

It's licensed GPL3 so shouldn't be a problem using some of it?

**Comment by DannyBen** [comment]
This is written in AutoHotkey - a very user friendly language.

To get the amount of the border offset is not really an issue - we can always set it in the config. On my system it looks like 8 pixels. So all that is left to do, is to make the proper adjustments when moving / resizing the window and extend the window by that many pixels.

I may give it some more attempts, but feel free to play with it also.

**Comment by fredkilbourn** [comment]
Gotcha, I'll try sometime if i can but don't know if it'll be super soon.

**Comment by DannyBen** [comment]
Adding some information to this ticket, for the future us.
To get the border width, we can use:

``` ahk
GetSideBorder() {
  SysGet out, 32
  Return out
}

GetTopBorder() {
  SysGet out, 33
  Return out
}
```

[As mentioned here](https://autohotkey.com/board/topic/93183-trouble-with-script-wingetpos/)

**Comment by DannyBen** [comment]
Hey - I have tried something that seems like working, if anyone wants to try.
The code is in the [win10 branch](https://github.com/DannyBen/Gridy/compare/win10?expand=1) and the exe can be [downloaded here](https://www.dropbox.com/s/4pqptln0xyk96ge/Gridy-win10-build.exe?dl=1)

**Comment by fredkilbourn** [comment]
Result:

![image](https://cloud.githubusercontent.com/assets/658757/15478882/b96802d2-20e2-11e6-85e1-c42934f03dfa.png)

Looks good so far, I'll let you know if I run into any more corner cases.

**Comment by fredkilbourn** [comment]
Office apps have some kind of different borders though - are hanging ~8 pixels over the edge of my monitor when aligned to the edge.  Skype has some strange behavior too when moving the window back and forth, sometimes off position by about ~8px.

**Comment by DannyBen** [comment]
Excellent.

Notes:
- The solution is a little tricky due to how Windows treats these borders, so different grid sizes MAY cause it to break. I think all grid sizes work, but not 100% sure
- Handling of the screen's edge may require more work. I focused on top and left edges, with the "Block" behavior. Havent tested others yet.
- If this works, I would probably want to make more adjustments to make the code less awkward.

In response to your second comment about different windows having different borders - this is one of the reasons I was reluctant to implement such a change. This whole Windows 10 transparent borders thing is a mess all around for many apps that rely on tight alignment.

I am not at all convinced that this is a good solution yet.

**Comment by fredkilbourn** [comment]
Just bumping on this issue as I still don't have time to invest in trying my own fix - I understand if you're busy too.

**Comment by fredkilbourn** [comment]
Hello again from the future.

**Comment by fightforlife** [comment]
I just found http://windowgrid.net/ which is working fine with all my programms and windows. 
Maybe you can use this for your app?

**Comment by DannyBen** [comment]
I am closing this as I do not see an easy solution.
If anyone has new information or suggestion for a fix, please open a new issue.

**Comment by ronald-jaepel** [comment]
Sorry to necrobump, but is that win10-branch exe still availeable? The dropboxlink leads to a 404.

**Comment by DannyBen** [comment]
I rebuilt and [updated the link](https://www.dropbox.com/s/4pqptln0xyk96ge/Gridy-win10-build.exe?dl=1)

**Comment by ronald-jaepel** [comment]
Awesome, works as expected (all window edges match, except for office-apps which overlap a bit, but not enough to bother me) Thank you so much!

**Comment by DannyBen** [comment]
Sure. 

I have also placed it in a GitHub release (marked as pre-release, to avoid shadowing the latest stable).
https://github.com/DannyBen/Gridy/releases/tag/v0.70-alt
