### ISSUE TITLE
Feature request: set interval for move / resize

### ISSUE THREAD

**Issue by mulderns** [DannyBen/Gridy#2]
Hello,

I'm making a request for option to set the interval for how fast the window move and resize operations operate. Now moving by holding the buttons down is a bit slow and you can do it faster by pressing the keys repeatedly. It would be in my opinion better if you could do fast moving whit holding buttons down and smaller, slower adjustments by repeatedly pressing the buttons.

**Comment by DannyBen** [comment]
Sounds to me like you need one of these two options:
1. Increase your keyboard repeat rate (see [this for how to](http://www.softwareok.com/?seite=faq-Windows-10&faq=51))
2. Change Gridy's settings to increase the grid size (right click the tray icon)

**Comment by mulderns** [comment]
Thanks! I had thought the grid size worked by dividing the screen.
