### ISSUE TITLE
"Single shortcut = multiple positions" idea

### ISSUE THREAD

**Issue by letmeindude** [DannyBen/Gridy#4]
I'm not good at explaining things, so I will try to show.

If you implement this feature, [Positions] part of the Gridy.ini could look like this (silly example):
```
[Positions]
Position1 =0,330,840,690
Position2 =0,330,1680,690
Position3 =840,330,840,690
Position4 =0,0,840,1020
Position5 =450,225,720,600
Position5 =405,165,900,720
Position5 =300,75,1155,915
Position6 =840,0,840,1020
Position7 =0,0,840,330
Position8 =0,0,1680,330
Position9 =840,0,840,330
Position10=128,64,512,512
Position11=544,64,512,512
Position12=768,64,512,512
```
Do you notice multiple Position5 entries? This means when you press Win+Numpad5 you will get:
Position5 =450,225,720,600

But if you press Numpad5 the second time you will get:
Position5 =405,165,900,720

And the third time you will get:
Position5 =300,75,1155,915

This is something like in Explorer, if you click once you select a file, but if you click twice you open a file.

Since we are talking about keyboard keys (no mouse "clicking like crazy" limitations) we can have as many positions as we want in a single shortcut (in my example, only 3 for Win+Numpad5).

This will not affect regular users, only those who open Gridy.ini and add their own multiple positions.
Gridy could show position of a active window in a tray icon tooltip. Currently it only shows %NameString% + %VersionString%.

So what do you think? Good idea or too much work for something which will only advanced users use?

**Comment by DannyBen** [comment]
Its a nice idea, but:

1. I am not in favor of features that can only be configured in the INI file. This is especially true for complex features, like writing window position manually.
2. The proposed configuration syntax will not work - INI file cannot have more than one key with the same name.
3. Yes, it is probably too much work... :)

**Comment by letmeindude** [comment]
Understandable, thank you for giving it a thought.
