### ISSUE TITLE
Please help me get this running.

### ISSUE THREAD

**Issue by LAPIII** [DannyBen/Gridy#5]
I got `Gridy.ahk` and `Gridy.ini `. 

1. Is there anything else that I need?
2. How do I edit `Gridy.ini`?

**Comment by DannyBen** [comment]
If you just want to use it (as opposed to develop it), then there is no need to get the AHK or INI file - just get the compiled executable here:
http://sector-seven.net/software/gridy

If you want to run it using the AutoHotkey source code, then you need to have AutoHotkey installed, and then you just run the `Gridy.ahk` file.

This is a Windows-only program, so if you are on a mac, it wont work.
