### ISSUE TITLE
Suggestion: cycling favourite presets.

### ISSUE THREAD

**Issue by AlanEdd** [DannyBen/Gridy#6]
Hey there,
This is wonderful, and just enough complexity without being too much.  I have changed the .ini file to use WIN+NUM1  for example to recall a preset, I feel it's less awkward than WIN+ALT. I would suggest some, hotkey or visual overlay that would illustrate the preset positions. (Probably more trouble than its worth)

This is the main suggestion:
Allow an assignable hotkey to cycle though favourites.  So there might be a hotkey say WIN+Z and that would cycle though presets 1,3,4,5 on each press of the same hotkey.

The favourites could be defined in the .ini.
favouritePresets=1,3,4,5
favouriteKey            =#z

Anyway thanks a lot for this software, its super. If you send me your email I'll send you a coffee to say thanks.

**Comment by DannyBen** [comment]
Hi Alan,

I am glad Gridy is still useful after all these years, and thank you for the coffee (and the big cake :) ).
I made Gridy a long time ago, when Windows did not yet have a native way of moving windows around with the keyboard. Today, Windows 11 has a similar functionality built in.

While Gridy still works on the latest versions of Windows, it is not being updated too much.

That said - I will take a look at the code next week, and see if this cycle button can be implemented easily.

**Comment by DannyBen** [comment]
After reviewing and trying to implement this, I realized it complicates the tool for what I suspect is an edge case.
It will not be implemented for the time being.

**Comment by AlanEdd** [comment]
No worries, thanks for looking into it.
I am using a batch file in windows to cycle through 3 positions as a type of hack, but it works fine for me!  It triggers different hotkeys (assigned by Gridy) based on the state of a variable.
